---
layout: single
title: "Python 예외 처리"
date: "2023-10-23 13:00:00 +0900"
last_modified_at: "2023-10-23 14:00:00 +0900"
author_profile: true
sidebar:
  nav: "main"
categories:
  - Python
---

예외처리 알아보기


## 예외처리?
.
```python
#예외처리

# try except 사용
# try 실행할 코드
# except 예외 발생시 처리코드

try:
    x = int(input('나눌 숫자 입력 : '))
    y = 10/ x
    print(y)


except:
    print('예외가 발생')

나눌 숫자 입력 : 55
0.18181818181818182

나눌 숫자 입력 : 0
예외가 발생

# 특정 예외만 처리

y = [10, 20, 30]
try:
    index, x = map(int, input('인덱스와 나눌 숫자 입력: ').split())
    print(y[index]/x)
except ZeroDivisionError:
    print('숫자를 0으로 어떻게 나눠요')
except IndexError:
    print('잘못된 인데스')

# 예외의 에러 메시지 받아오

y = [10, 20, 30]
try:
    index, x = map(int, input('인덱스와 나눌 숫자 입력: ').split())
    print(y[index]/x)
except ZeroDivisionError as e:
    print('숫자를 0으로 어떻게 나눠요', e)
except IndexError as e:
    print('잘못된 인데스', e)

인덱스와 나눌 숫자 입력: 2 0
숫자를 0으로 어떻게 나눠요 division by zero

인덱스와 나눌 숫자 입력: 3 5
잘못된 인데스 list index out of range

# else, finally
# else 예외가 발생하지 않았을 때 실행할 코드
# finally 예외 여부 상관없이 항상 실행코드

try :
    x = int(input('나눌 숫자를 입력 : '))
    y= 10/ x
except ZeroDivisionError:
    print('숫자를 0으로 나눌 수 없어요')
else:
    print(y)
finally:
    print('코드 실행 끝')

나눌 숫자를 입력 : 2
5.0
코드 실행 끝

### try 안에서 만든 변수는 밖에서도 사용 가능. try는 함수가 아니라 스택프레임을 만들지 않음. except, else, finally도 마찬가지
```
```python
# 예외 발생시키기
try:
    x = int(input('3의 배수를 입력하세요 : '))
    if x % 3 != 0:
        raise Exception('3의 배수가 아닙니다')
    print(x)
except Exception as e:
    print('예외가 발생했습니다.', e)

3의 배수를 입력하세요 : 32
예외가 발생했습니다. 3의 배수가 아닙니다
```
```python
# raise 처리과정

def three_multiple():
    x = int(input('3의 배수를 입력하세요: '))
    if x % 3 != 0:
        raise Exception('3의 배수가 아닙니다') #try except 없는 상태에서 raise로 예외발생
    print(x)
try:
    three_multiple()
except Exception as e:
    print('예외가 발생했습니다', e)
3의 배수를 입력하세요: 32
예외가 발생했습니다 3의 배수가 아닙니다

# 현재 예외 다시 발생시키기
def three_multiple():
    try:
        x = int(input('3의 배수를 입력하세요: '))
        if x % 3 != 0:
            raise Exception('3의 배수가 아닙니다')
        print(x)
    except Exception as e:
        print('three_multiple 함수에서 예외가 발생했습니다.', e)
        raise

try:
    three_multiple()
except Exception as e:
    print('예외가 발생했습니다', e)

3의 배수를 입력하세요: 31
three_multiple 함수에서 예외가 발생했습니다. 3의 배수가 아닙니다
예외가 발생했습니다 3의 배수가 아닙니다
```
```python
# 예외 만들기
class NotThreeMultitierror(Exception): # Exception 상속받음
    def __init__(self):
        super().__init__('3의 배수가 아닙니다')

def three_mulitple():
    try:
        x = int(input('3의 배수 입력: '))
        if x%3!=0:
            raise NotThreeMultitierror # 아래 print 안거치고 바로 호
        print(x) 
    except Exception as e:
        print('예외 발생',e)

three_mulitple()

3의 배수 입력: 5
예외 발생 3의 배수가 아닙니다
```